project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include(('simpleapp.urls', 'simpleapp'), namespace='news')),
    path('news/', include('simpleapp.urls')),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
]

project/sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import BaseRegisterView, upgrade_me

urlpatterns = [
    path('login/', LoginView.as_view(template_name='sign/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='sign/logout.html'), name='logout'),
    path('signup/', BaseRegisterView.as_view(template_name='sign/signup.html'), name='signup'),
    path('upgrade/', upgrade_me, name='upgrade'),
]

project/simpleapp/urls.py
from .views import NewList, NewDetailView, Search, NewCreateView, NewDeleteView, NewUpdateView, subscribe_me
from django.urls import path, include


urlpatterns = [
    path('', NewList.as_view()),
    path('<int:pk>', NewDetailView.as_view(), name='new'),
    path('search/', Search.as_view()),
    path('create/', NewCreateView.as_view(), name='new_create'),
    path('<int:pk>/update/', NewUpdateView.as_view(), name='new_update'),
    path('<int:pk>/delete/', NewDeleteView.as_view(), name='new_delete'),
    path('<int:pk>/subscribe/', subscribe_me, name='subscribe'),

]

project/templates/new.html
{% extends 'flatpages/default.html' %}

{% block title %}
  {{ new.new_name }}
{% endblock title %}

{% block content %}
  <table>
      <thead>
          <th>
              Название
          </th>
          <th>
              Дата публикации
          </th>
          <th>
              Содержание
          </th>
      </thead>
      <tr>
          <td>
              {{ new.post_name }}
          </td>
          <td>
              {{ new.created | date:'d M Y' }}
          </td>
          <td>
              {{ new.content }}
          </td>
      </tr>
  </table>
    {% if is_not_subscribe %}
        <button> <a href="{% url 'news:subscribe' new.id %}">Подписаться</a> </button>
    {% endif %}
{% endblock content %}

project/templates/new_create.html
{% extends 'flatpages/default.html' %}

{% block title %} Создание записи {% endblock title %}

{% block content %}
    <h3>Информация о новой записи</h3>
    <form method="POST">
        {% csrf_token %}
        {{ form }} <!-- Теперь нам нужна только готовая форма и кнопка -->
        <input type="submit" value="Добавить запись">
    </form>
{% endblock content %}

project/templates/new_delete.html
{% extends 'flatpages/default.html' %}

{% block title %}
  {{ post.post_name }}
{% endblock title %}

{% block content %}
  <h2>Вы действительно хотите удалить данную запись?</h2>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="удалить">
    </form>
{% endblock content %}

project/templates/new_update.html
{% extends 'flatpages/default.html' %}
{% block title %}
  редактирование
{% endblock title %}


{% block content %}
    <title>Кнопка</title>
    <form method="POST">
        {% csrf_token %}
        {{ form }} <!-- Теперь нам нужна только готовая форма и кнопка -->
        <input type="submit" value="Редактировать запись">
    </form>

{% endblock content %}

project/templates/news.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
    Новости
{% endblock title %}

<!-- post_name - переменная для доступа к полю имени объекта-->
{% block content %}

<style type="text/css">
   .indentation {
       padding: 10px 15px 5px 15px;
   }
   .indentation_for_txt{
       padding: 3px 15px 3px 15px;
   }
</style>

    <h2>Все новости</h2>
    <h3>Общее количество: {{ news | length }}</h3>
    <hr>
    <form method="GET">
        {{ filter.form }}
        <input type="submit" value="Найти">
    </form>
    <hr>
    {% if news %}
        <table>
            <tr>
                <td class="indentation">
                    Автор
                </td>
                <td class="indentation">
                    Рэйтинг
                </td>
                <td class="indentation">
                    Название
                </td>
                <td class="indentation">
                    Дата публикации
                </td>
                <td class="indentation">
                    Содержание
                </td>
                <td class="indentation">
                    Действия
                </td>
            </tr>
            <!-- проходимся new по фильтру -->
        {% for new in filter.qs %}
            <tr>
                <td class="indentation_for_txt">
                    {{ new.author }}
                </td>
                <td class="indentation_for_txt">
                    {{ new.rating_new }}
                </td>
                <td class="indentation_for_txt">
                    <a href="{% url 'new' new.id %}">{{ new.post_name }}</a>
                </td>
                <td class="indentation_for_txt">
                    {{ new.created | date:'d M Y' }}
                </td>
                <td class="indentation_for_txt">
                    {{ new.content | truncatechars:50 }}
                </td>
                    <td class="indentation_for_txt">
                        <a href="{% url 'new_update' new.id %}"><u>Редактировать</u></a>
                     <a href="{% url 'new_delete' new.id %}"><u> Удалить </u></a>
                    </td>
            </tr>
        {% endfor %}
        </table>
        <hr>
        <a href="{% url 'new_create' %}">Добавить новую запись</a> <br>
        <hr>
        {% if is_paginated %}

            {% if page_obj.has_previous %}
                <a href="?page=1">First</a>
                <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a>{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">>>></a>
                <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}

        {% endif %}
    {% else %}
        <h2>Новостей нет.</h2>
        <a href="{% url 'new_create' %}">Добавить новую запись</a> <br>
    {% endif %}
{% endblock content %}

project/templates/product.html
<!--  наследуемся от шаблона default.html, который мы создавали ещё во времена flatpages -->
{% extends 'flatpages/default.html' %}

<!-- Название у нас будет proudcts -->
{% block title %}
Products
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, айди которого было передано в адрес -->
{% block content %}
<h1>{{ product }}</h1>
{% endblock content %}

project/templates/products.html
{% extends 'flatpages/default.html' %}

{% block title %}
Products
{% endblock title %}

{% block content %}
    <h1>Все товары</h1>
    <h3>{{ time_now|date:'M d Y' }}</h3> <!-- Здесь мы применяем фильтр date. Он очень похож на метод strftime у даты. С его помощью мы можем выводить дату в нужном нам формате -->
    <hr>
    {% if products %}
        <table>
            <tr>
                <td>
                    Название
                </td>
                <td>
                    Описание
                </td>
                <td>
                    Категория
                </td>
                <td>
                    Цена
                </td>
                <td>
                    Количество
                </td>
            </tr>
        {% for product in products %}
            <tr>
                <td>
                    {{ product.name }}
                </td>
                <td>
                    {{ product.description|truncatewords:4 }}
                </td>
                <td>
                    {{ product.category.name }}
                </td>
                <td>
                    {{ product.price }}
                </td>
                <td>
                    {{ product.quantity }}
                </td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <h2>Товаров нет!</h2>
    {% endif %}
{% endblock content %}